//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Id_Admin { get; set; }
        public Nullable<int> Id_pegawai { get; set; }
        public string User_name { get; set; }
        public string Password { get; set; }
    
        public virtual Pegawai Pegawai { get; set; }
    }
}
