//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HospitalEntities : DbContext
    {
        public HospitalEntities()
            : base("name=HospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Kamar> Kamars { get; set; }
        public DbSet<Patient> Patients { get; set; }
        public DbSet<Pegawai> Pegawais { get; set; }
        public DbSet<Periksa> Periksas { get; set; }
    
        public virtual ObjectResult<Nullable<int>> GetNewAdminId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewAdminId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewKamarId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewKamarId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewPatientId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewPatientId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewPegawaiId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewPegawaiId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetNewPeriksaId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetNewPeriksaId");
        }
    }
}
