//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kamar
    {
        public Kamar()
        {
            this.Patients = new HashSet<Patient>();
        }
    
        public int Id_Room { get; set; }
        public string Nama_Kamar { get; set; }
        public int Harga_Sewa { get; set; }
        public byte Status_Kamar { get; set; }
    
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
