//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pegawai
    {
        public Pegawai()
        {
            this.Admins = new HashSet<Admin>();
            this.Patients = new HashSet<Patient>();
            this.Periksas = new HashSet<Periksa>();
        }
    
        public int ID_Pegawai { get; set; }
        public string Jenis_Pegawai { get; set; }
        public string Nama_Pegawai { get; set; }
        public string Alamat_Pegawai { get; set; }
        public Nullable<int> Telp_Pegawai { get; set; }
        public string Kota { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Admin> Admins { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual ICollection<Periksa> Periksas { get; set; }
    }
}
