//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periksa
    {
        public int No_Pemeriksaan { get; set; }
        public Nullable<int> id_Pegawai { get; set; }
        public Nullable<int> id_Pasien { get; set; }
        public string Penyakit_Akhir { get; set; }
        public int Tarif { get; set; }
        public string Status_Rawat { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Pegawai Pegawai { get; set; }
    }
}
